## Using genomepy

### How to use genomepy

`genomepy` is another tool designed for searching and downloading genomic data. It can be used to:

1. search available data
2. show the available metadata
3. automatically download, preprocess
4. generate optional aligned indexes

Currently, `genomepy` supports Ensembl, UCSC, NCBI, and GENCODE.

<center>

```{mermaid}
flowchart LR
  genomepy["`**genomepy**`"]
  commands{"`**search**
  **install**
  **annotation**`"}
  storage["`files stored in
  **$home/local/share/genomes**`"]
  
  genomepy --> commands --> storage
```

</center>

See also: [genomepy documentation](https://github.com/vanheeringen-lab/genomepy)

### Installation

Install using micromamba:
```bash
micromamba install genomepy
```

Install using pip or pipx:
```bash
pipx install genomepy
```

### Using genomepy

Use the `search` command to query genomes by name or accession:
```bash
genomepy search ecoli > ecoli_query_results.txt
```

A genome index will be downloaded upon invoking the `search` command for the first time. Hence, the initial search may take a while depending on your connection speed. As seen from the log below, assembly summaries are fetched from multiple databases (GENCODE, UCSC, Ensembl, NCBI).

```md
05:28:31 | INFO | Downloading assembly summaries from GENCODE
05:29:54 | INFO | Downloading assembly summaries from UCSC
05:30:05 | INFO | Downloading assembly summaries from Ensembl
05:30:43 | INFO | Downloading assembly summaries from NCBI, this will take a while...
genbank_historical: 73.0k genomes [00:06, 11.1k genomes/s]
refseq_historical: 85.6k genomes [00:05, 16.6k genomes/s]
genbank: 2.39M genomes [02:11, 18.1k genomes/s]
refseq: 378k genomes [00:28, 13.0k genomes/s] 
```

The results look like so:
```md
name                 provider accession         tax_id annotation species                                  other_info                              
                                                        n r e k   <- UCSC options (see help)                                                       
EcoliT22_2.0         NCBI     GCF_000247665.3      562     ✓      Escherichia coli O157:H43 str. T22       BAYGEN                                  
Ecoli.O104:H4.LB226692_2.0 NCBI     GCA_000215685.3      562     ✓      Escherichia coli O104:H4 str. LB226692   Life Technologies                       
Ecoli.O104:H4.01-09591_1.0 NCBI     GCA_000221065.2      562     ✓      Escherichia coli O104:H4 str. 01-09591   Life Technologies                       
Ecoli_C227-11_1.0    NCBI     GCA_000220805.2      562     ✓      Escherichia coli O104:H4 str. C227-11    PacBio                                  
ecoli009             NCBI     GCA_900607665.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL         
ecoli006             NCBI     GCA_900607465.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL         
ecoli008             NCBI     GCA_900607535.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL         
ecoli017             NCBI     GCA_900608025.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL         
ecoli025             NCBI     GCA_900608175.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL         
ecoli022             NCBI     GCA_900608105.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL         
ecoli015             NCBI     GCA_900607975.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL         
ecoli013             NCBI     GCA_900607805.1      562     ✓      Escherichia coli                         BIOZENTRUM, UNIVERSITY OF BASEL       
```

Entries under the `name` field can be used to download the genome:
```bash
genomepy install ecoli009
```

By default, the downloaded genomes will be found in the `~/.local/share/genomes` directory. For our example, the directory named `ecoli009` contains the genome data and other relevant files:

```{python}
#| echo: false
#| eval: true

! tree ~/.local/share/genomes
```