## How to use refgenie

Refgenie is a command-line tool that can be used to download and manage reference genomes, and to build and manage custom genome assets. It also provides a Python interface for programmatic access to genome assets.

<center>

```{mermaid}
flowchart LR
  list["`**refgenie**
  list`"]
  pull["`**refgenie**
  pull`"]
  seek["`**refgenie**
  seek`"]
  list --> pull --> seek
```

</center>

### Installation

Refgenie can be installed as a Python package using `pip`:

```sh
pip install --user refgenie

# Use pipx instead of pip
pipx install refgenie
```

or conda:

```sh
conda install -c conda-forge refgenie

# Use mamba/micromamba instead of conda
micromamba install refgenie
```

### Create a config file

`refgenie` requires a configuration file that lists the resources in the form of a yaml file. For that you need to select a directory that will store the downloaded resources. The path to the config file is saved as the `REFGENIE` shell environment variable which will be used for initialization:

```sh
# Store path to config as an environment variable
export REFGENIE=~/refs/config.yaml

# Load the REFGENIE variable when launching a shell instance
echo "export REFGENIE=~/refs/config.yml" >> ~/.bashrc
source ~/.bashrc

# Run initialization
refgenie init
```

The `refgenie` tool is now ready to be used to download and manage reference genomes.

### Using refgenie

A list of pre-built assets from a remote server can be displayed with `listr`:

```sh
refgenie listr
```

Refrence genome data is fetched using the `pull` command and the path to the download is retrieved using the `seek` command.

```sh
# Downloads the hg38 bwa index
refgenie pull hg38/bwa_index

# Prints the path to the downloaded hg38 bwa index
refgenie seek hg38/bwa_index
```

List local genome assets:

```sh
refgenie list
```

Use command substitution to store the genome path to a variable:

```sh
# Retrieve the human reference genome
refgenie pull hg38/fasta

# Save path of reference genome to a variable
REF=$(refgenie seek hg38/fasta)
```

Then use the resulting path in downstream tools:

```sh
# Generate statistics for the human reference genome
seqkit stats ${REF}
```

Subscribe to the iGenomes server which hosts additional reference genomes and genome assets.

```sh
refgenie subscribe -s http://igenomes.databio.org/
```
