project:
  type: website
  output-dir: docs

website:
  title: "BioHub"
  navbar:
    background: dark
    foreground: light
    left:
      - href: notebook.qmd
        text: "Notebook"
      - href: rosalind.qmd
        text: "Rosalind"
    tools:
      - icon: twitter
        href: https://x.com/dagsdags13
      - icon: github
        href: https://github.com/dagsdags212
format:
  html:
    theme: 
      - cosmo
      - custom.scss 
    toc: false
    css: styles.css


bibliography: references.bib
highlight-style: monokai
code-annotations: hover
code-overflow: scroll

