project:
  type: website
  output-dir: docs

website:
  title: "BioHub"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: © 2024, Jan Samson
  navbar:
    background: dark
    foreground: light
    pinned: false
    left:
      - href: pages/notebook.qmd
        text: "Notebook"
      - href: pages/lab.qmd
        text: "Lab"
      - href: pages/algorithms.qmd
        text: "Algorithms"
      - href: pages/rosalind.qmd
        text: "Rosalind"
    tools:
      - icon: twitter
        href: https://x.com/dagsdags13
      - icon: github
        href: https://github.com/dagsdags212

format:
  html:
    theme: [cosmo]
    toc: true
    toc-location: left
    css: ./css/styles.css

filters:
  - include-code-files

bibliography: references.bib
highlight-style: monokai
code-annotations: hover
code-overflow: scroll
