project:
  type: website
  output-dir: docs

highlight-style: ayu
code-annotations: hover

execute:
  warning: false
  error: false
  cache: true

website:
  title: "BioHub"
  site-url: https://dagsdags212.github.io/biohub
  description: "all things bioinformatics and more"
  page-navigation: true

  # options
  reader-mode: false
  back-to-top-navigation: true
  repo-url: https://github.com/dagsdags212/biohub
  repo-branch: main

  # footer
  page-footer:
    left: ""
    right:
      - icon: github
        href: https://github.com/dagsdags212 

  # nav
  navbar:
    background: dark
    foreground: light
    pinned: false
    left:
      - href: pages/notebook.qmd
        text: "Notebook"
      - href: pages/lab.qmd
        text: "Lab"
      - href: pages/algorithms.qmd
        text: "Algorithms"
      - href: pages/rosalind.qmd
        text: "Rosalind"
    tools:
      - icon: twitter
        href: https://x.com/dagsdags13
      - icon: github
        href: https://github.com/dagsdags212

format:
  html:
    theme: 
      light: [flatly, css/theme_light.scss]
      dark: [darkly, css/theme_dark.scss]
    css: css/styles.css
    toc: true
    toc-location: left

filters:
  - include-code-files

code-overflow: scroll
