### The Entrez System Identifies Database Records Using UIDs

::: {.callout-note title="Unique Identifiers"}
Each data record stored in an Entrez database is associated with a **unique identifier** (UID).
:::

| Entrez Database | UID Common Name | E-utility Database Name | 
| ----- | ----- | ----- |
| BioProject | BioProject ID | bioproject | 
| BioSample | BioSample ID | biosample | 
| Books | Book ID | books | 
| Conserved Domains | PSSM-ID | cdd | 
| dbGaP | dbGaP ID | gap | 
| dbVar | dbVar ID | dbvar | 
| Gene | Gene ID | gene | 
| GEO Datasets | GDS ID | gds | 
| GEO Profiles | GEO ID | geoprofiles | 
| HomoloGene | HomoloGene ID | homologene | 
| MeSH | MeSH ID | mesh | 
| NCBI C++ Toolkit | Toolkit ID | toolkit | 
| NLM Catalog | NLM Catalog ID | nlmcatalog | 
| Nucleotide | GI number | nuccore | 
| PopSet | PopSet ID | popset | 
| Probe | Probe ID | probe | 
| Proteins | GI number | proteins | 
| Protein Clusters | Protein Cluser ID | proteinclusters | 
| PubChem BioAssay | AID | pcassay | 
| PubChem Compound | CID | pccompound | 
| PubChem Substance | SID | pcsubstance | 
| PubMed | PMID | pubmed | 
| PubMed Central | PMCID | pmc | 
| SNP | rs number | snp | 
| SRA | SRA ID | sra | 
| Structure | MMDB-ID | structure | 
| Taxonomy | TaxID | taxonomy | 
: Entrez Unique Identifiers (UIDs) for selected databases. {.hover .striped}

The list of E-utility database names can also be retrieved by running the `einfo` command:
```bash
einfo -email $EMAIL -dbs | sort
```
